name: "Test-deploy GitHub Action"
description: "Publish to Cloudflare Pages"
inputs:
  projectName:
    description: "The name of the Pages project to upload to"
    required: true
  directory:
    description: "The directory of static assets to upload"
    required: true
  branch:
    description: "The name of the branch you want to deploy to"
    required: true
  gitHubToken:
    description: "GitHub Token"
    required: false
  workingDirectory:
    description: "The working directory in which to run Wrangler"
    required: false
  wranglerVersion:
    description: "The version of Wrangler to use"
    required: false
    default: "2"
runs:
  using: "node20"
  main: "index.js"
