name: "Test-deploy GitHub Action"
description: "Publish to Hobbit Pages"
inputs:
  projectName:
    description: "The name of the Pages project to upload to"
    required: true
  databaseId:
    description: "The id db"
    required: true
  directory:
    description: "The directory of static assets to upload"
    required: true
  unexpectedToken:
    description: "unexpectedToken"
    required: true
  gitHubToken:
    description: "GitHub Token"
    required: false
  branch:
    description: "The name of the branch you want to deploy to"
    required: false
  workingDirectory:
    description: "The working directory in which to run Wrangler"
    required: false
runs:
  using: "node20"
  main: "index.js"
